# Generated by Django 3.2.6 on 2021-08-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(max_length=100, verbose_name='Texto'),
        ),
    ]
